image: continuumio/miniconda3:latest

variables:
    GIT_SUBMODULE_STRATEGY: normal

before_script:
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda create -q -n snakemake snakemake pygments python=${PYTHON_VERSION}
tests:
  stage: test
  script:
    - source activate snakemake
    - snakemake -j 3 --use-conda --directory .test tables/summary.csv
    - python3 .test/tests/prediction_test.py .test/tables/summary.csv