projects : 'projects.tsv'                                      # TCGA projects to parse
inputdir : '/home/sagarcia/Documents/TFM/RAW/PAN-TCGA'          # Where to look for said projects
outdir   : '/home/sagarcia/Documents/TFM/GENERATED/TCGA'       # Where to save resutls
logdir   : 'log/test'                                          # Where to save events log.

rules:
    default:
        res:
            threads: 1
            mem:  2048

    # These rules are using python3 pandas vector operations, which are
    # single threaded. There is no advantage to more threads. Memory can
    # be tweaked though.

    rebuild_vulcan_database:      # Requires internet connection
        threads: 1
        mem:  2048
    rebuild_snp_array_dictionary: # Requires internet connection
        threads: 1
        mem: 2048
    rebuild_rnaseq_dictionary:    # Requires internet connection
        threads: 1
        mem: 2048
    rebuild_gscore_database: 
        threads: 1
        mem: 2048
    filter_maf_files: 
        threads: 1 
        mem: 2048
    filter_cnv_files:
        threads: 1
        mem: 2048
    filter_mrna_files:
        threads: 1
        mem: 4096
    generate_cases_table:
        threads: 1
        mem: 2048
    vulcanspot_annotation:
        threads: 1
        mem: 2048
    generate_summary_plots:
        threads: 1
        mem: 2048
